version: "3.8"

networks:
  coderithm_network:

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: coderithm
    ports:
      - "5432:5432"
    networks:
      - coderithm_network
